### ISSUE TITLE
Error using 'restart' command in Web-UI

### ISSUE THREAD

**Issue by fade2gray** [romanvm/kodi.web-pdb#19]
Windows 10; Python 3.8.5; Kodi 18.8; Web-PDB 1.5.4

Hello,

I am new to addon development and have been experimenting with your 'Example Kodi Video Plugin',  but I find I get an error when using the 'restart' command in the web-UI.

Do you have any advice please?

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'pdb.Restart'>
    Traceback (most recent call last):
      File "C:\Users\fade2gray\AppData\Roaming\Kodi\addons\plugin.video.example\main.py", line 16, in <module>
        _url = sys.argv[0]
      File "C:\Users\fade2gray\AppData\Roaming\Kodi\addons\plugin.video.example\main.py", line 16, in <module>
        _url = sys.argv[0]
      File "C:\Program Files\Kodi\system\python\Lib\bdb.py", line 49, in trace_dispatch
        return self.dispatch_line(frame)
      File "C:\Program Files\Kodi\system\python\Lib\bdb.py", line 67, in dispatch_line
        self.user_line(frame)
      File "C:\Program Files\Kodi\system\python\Lib\pdb.py", line 158, in user_line
        self.interaction(frame, None)
      File "C:\Program Files\Kodi\system\python\Lib\pdb.py", line 210, in interaction
        self.cmdloop()
      File "C:\Program Files\Kodi\system\python\Lib\cmd.py", line 142, in cmdloop
        stop = self.onecmd(line)
      File "C:\Program Files\Kodi\system\python\Lib\pdb.py", line 279, in onecmd
        return cmd.Cmd.onecmd(self, line)
      File "C:\Program Files\Kodi\system\python\Lib\cmd.py", line 221, in onecmd
        return func(arg)
      File "C:\Program Files\Kodi\system\python\Lib\pdb.py", line 679, in do_run
        raise Restart
    Restart
    -->End of Python script error report<--
```

**Comment by romanvm** [comment]
`restart` command works only if a Python script was launched by PDB debugger itself that is not possible inside Kodi. You need to restart your addon maually.  I guess I need to add caveat to the project Readme.

BTW, Kodi 18 uses Python 2.7, not 3.8.

**Comment by fade2gray** [comment]
Thanks for the explanation.

Python 3.8.5 - an unrequired reference to the version installed on my PC. :/

**Comment by romanvm** [comment]
This is actually a limitation of the built-in PDB: `run`/`restart` comand does not work if a debugging session started with set_trace() or breakpoint() calls.
