### ISSUE TITLE
web-pdb crashes with error

### ISSUE THREAD

**Issue by jmooremcc** [romanvm/kodi.web-pdb#5]
I only have one breakpoint set and get the following error:

```
 15:55:52.030 T:1424696224   ERROR: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.web-pdb/libs/web_pdb/asyncore_wsgi/__init__.py", line 148, in handle_write
                                                handler.run(self.server.get_app())
                                              File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
                                              File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
                                            AttributeError: 'NoneType' object has no attribute 'split'

```
The display in the browser has all screens white with no information in them
I'm running on a Raspberry Pi, LE 8.2.4, Linux 4.9.59, Kodi 17.6

**Comment by romanvm** [comment]
I need full full information: your full debug log and the code that you are trying to debug. Also please use GitHub Markdown to properly format your messages.

**Comment by jmooremcc** [comment]
Problem Solved.
Problem with display was related to Chrome browser.
Had to use incognito mode to get  it to work.
Was able to set break points and step through the code as expected.
Thanks
